name:                aoc2021
version:             0.1.0.0
github:              "envp/adventofcode"
license:             MIT
author:              "Vaibhav Yenamandra"
maintainer:          "envp@calloc.net"
copyright:           "2021 Vaibhav Yenamandra"

extra-source-files:
- README.md
- ChangeLog.md

description: My solutions to Advent of Code 2021

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - lib

_exe-defs: &exe-defaults
  ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - aoc2021

executables:
  day01:
    <<: *exe-defaults
    source-dirs: src/day01
    main: Main.hs
  day02:
    <<: *exe-defaults
    source-dirs: src/day02
    main: Main.hs
  day03:
    <<: *exe-defaults
    source-dirs: src/day03
    main: Main.hs
  day04:
    <<: *exe-defaults
    source-dirs: src/day04
    main: Main.hs

tests:
  aoc2021-test:
    <<: *exe-defaults
    source-dirs: test
    main: Spec.hs
