name:                aoc2021
version:             0.1.0.0
github:              "envp/adventofcode"
license:             MIT
author:              "Vaibhav Yenamandra"
maintainer:          "envp@calloc.net"
copyright:           "2021 Vaibhav Yenamandra"

extra-source-files:
- README.md
- ChangeLog.md

description: My solutions to Advent of Code 2021

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
